### ISSUE TITLE
Invalid method name 'getClusterInfo'

### ISSUE THREAD

**Issue by pkadetiloye** [wurstmeister/storm-docker#11]
I got this error message while deploying my topology? I can't seems to figure it out, why ?

````
development/storm/apache-storm-0.9.3/bin -Dstorm.jar=storm-starter-0.0.1-SNAPSHOT.jar storm.starter.ExclamationTopology ExTopo
Exception in thread "main" java.lang.RuntimeException: org.apache.thrift7.TApplicationException: Invalid method name: 'getClusterInfo'
        at backtype.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:211)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:117)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:70)
        at storm.starter.ExclamationTopology.main(ExclamationTopology.java:59)
Caused by: org.apache.thrift7.TApplicationException: Invalid method name: 'getClusterInfo'
        at org.apache.thrift7.TApplicationException.read(TApplicationException.java:108)
        at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:71)
        at backtype.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:468)
        at backtype.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:456)
        at backtype.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:202)
        ... 3 more
````

**Comment by pkadetiloye** [comment]
My bad, I figured it out, wasn't deploying my topology correctly.

**Comment by rkuris** [comment]
I'm getting this same error @pkadetiloye, can you describe what you were doing wrong when you deployed your topology and got this error?

**Comment by rkuris** [comment]
In case someone else finds this page, the problem was I was using the wrong port (3772 or 3773). Thrift listens on 6627, and so when using storm-docker, the UI didn't show that mapping for some reason. Making the window wider showed the correct port (or clicking on the gear icon).

**Comment by mavencode01** [comment]
@rkuris that's correct...thanks!
