### ISSUE TITLE
jdk 1.8?

### ISSUE THREAD

**Issue by tysonnorris** [wurstmeister/storm-docker#14]
Any intention to support jdk 1.8 here?
Thanks!
Tyson

**Comment by mavencode01** [comment]
+1, I deployed my topology but one of the libraries in my project requires jdk 1.8
How can I update the docker image ?

```
2015-05-22 11:24:50 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.UnsupportedClassVersionError: edu/stanford/nlp/pipeline/StanfordCoreNLP : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_65]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_65]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_65]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_65]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_65]
```
